import { handleAuth } from '@auth0/nextjs-auth0';

console.log('ENV CONFIG:', {
    NEXT_PUBLIC_AUTH0_SECRET: process.env.NEXT_PUBLIC_AUTH0_SECRET,
    NEXT_PUBLIC_AUTH0_BASE_URL: process.env.NEXT_PUBLIC_AUTH0_BASE_URL,
    NEXT_PUBLIC_AUTH0_ISSUER_BASE_URL: process.env.NEXT_PUBLIC_AUTH0_ISSUER_BASE_URL,
    NEXT_PUBLIC_AUTH0_CLIENT_ID: process.env.NEXT_PUBLIC_AUTH0_CLIENT_ID,
    NEXT_PUBLIC_AUTH0_CLIENT_SECRET: process.env.NEXT_PUBLIC_AUTH0_CLIENT_SECRET,
  });
  
export const { GET, POST } = handleAuth();