import type {Metadata}
from "next";
import "./globals.css";
import Footer from "@/Components/Footer/Footer";
import Navbar from "@/Components/Navbar/Navbar";
import SideBar from "@/Components/SideBar/SideBar";
import ContextWrapper from "./Utils/Context/Contexts";
import QuickCart from "@/Components/QuickCart/QuickCart";
import PerksSection from "@/Components/PerksSection/PerksSection";

export const metadata : Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({children} : Readonly < {
    children: React.ReactNode;
} >) {
    return (
        <html lang="en">
            <body>
            <ContextWrapper>

                <Navbar/>
                <SideBar/>
                <QuickCart/>
                 {children}
                <PerksSection/>
                <Footer/>
            </ContextWrapper>
            </body>
        </html>
    );
}
